INSERT INTO word (difficulty, example, meaning, word) VALUES (0, 'You can apply for the job online.', '지원하다', 'Apply');
INSERT INTO word (difficulty, example, meaning, word) VALUES (0, 'Please read the notice on the wall.', '공고, 통지', 'Notice');
INSERT INTO word (difficulty, example, meaning, word) VALUES (0, 'All staff members must attend the meeting.', '직원', 'Staff');
INSERT INTO word (difficulty, example, meaning, word) VALUES (0, 'The technician will repair the copier.', '수리하다', 'Repair');
INSERT INTO word (difficulty, example, meaning, word) VALUES (0, 'I received your email yesterday.', '받다', 'Receive');
INSERT INTO word (difficulty, example, meaning, word) VALUES (0, 'The meeting starts at ten.', '회의', 'Meeting');
INSERT INTO word (difficulty, example, meaning, word) VALUES (0, 'Our office is on the third floor.', '사무실', 'Office');
INSERT INTO word (difficulty, example, meaning, word) VALUES (0, 'Please read this report.', '보고서', 'Report');
INSERT INTO word (difficulty, example, meaning, word) VALUES (0, 'We are waiting for the client.', '고객', 'Client');
INSERT INTO word (difficulty, example, meaning, word) VALUES (0, 'I would like to order a laptop.', '주문하다', 'Order');
INSERT INTO word (difficulty, example, meaning, word) VALUES (0, 'The service here is excellent.', '서비스', 'Service');
INSERT INTO word (difficulty, example, meaning, word) VALUES (0, 'Check the schedule before leaving.', '확인하다', 'Check');
INSERT INTO word (difficulty, example, meaning, word) VALUES (0, 'The price is very reasonable.', '가격', 'Price');
INSERT INTO word (difficulty, example, meaning, word) VALUES (0, 'The store opens at 9 AM.', '상점', 'Store');
INSERT INTO word (difficulty, example, meaning, word) VALUES (0, 'I travel for work often.', '여행하다', 'Travel');
INSERT INTO word (difficulty, example, meaning, word) VALUES (0, 'Please visit our website.', '방문하다', 'Visit');
INSERT INTO word (difficulty, example, meaning, word) VALUES (0, 'How can I help you?', '돕다', 'Help');
INSERT INTO word (difficulty, example, meaning, word) VALUES (0, 'Send me an email later.', '이메일', 'Email');
INSERT INTO word (difficulty, example, meaning, word) VALUES (0, 'The phone is ringing.', '전화', 'Phone');
INSERT INTO word (difficulty, example, meaning, word) VALUES (0, 'Write your name here.', '쓰다', 'Write');
INSERT INTO word (difficulty, example, meaning, word) VALUES (0, 'They work in the city.', '일하다', 'Work');
INSERT INTO word (difficulty, example, meaning, word) VALUES (0, 'We have no time to waste.', '시간', 'Time');
INSERT INTO word (difficulty, example, meaning, word) VALUES (0, 'I need more information.', '정보', 'Information');
INSERT INTO word (difficulty, example, meaning, word) VALUES (0, 'Answer the question, please.', '대답하다', 'Answer');
INSERT INTO word (difficulty, example, meaning, word) VALUES (0, 'Do you have any questions?', '질문', 'Question');
INSERT INTO word (difficulty, example, meaning, word) VALUES (0, 'This company is very big.', '회사', 'Company');
INSERT INTO word (difficulty, example, meaning, word) VALUES (0, 'Which department do you work in?', '부서', 'Department');
INSERT INTO word (difficulty, example, meaning, word) VALUES (0, 'Talk to the manager.', '관리자', 'Manager');
INSERT INTO word (difficulty, example, meaning, word) VALUES (0, 'Business is going well.', '사업, 업무', 'Business');
INSERT INTO word (difficulty, example, meaning, word) VALUES (0, 'This is our new product.', '제품', 'Product');
INSERT INTO word (difficulty, example, meaning, word) VALUES (0, 'The sale ends tomorrow.', '판매', 'Sale');
INSERT INTO word (difficulty, example, meaning, word) VALUES (0, 'The customer is always right.', '고객', 'Customer');
INSERT INTO word (difficulty, example, meaning, word) VALUES (0, 'I sent a letter to him.', '편지', 'Letter');
INSERT INTO word (difficulty, example, meaning, word) VALUES (0, 'We need more paper.', '종이, 서류', 'Paper');
INSERT INTO word (difficulty, example, meaning, word) VALUES (0, 'I want to book a room.', '예약하다', 'Book');
INSERT INTO word (difficulty, example, meaning, word) VALUES (0, 'Make a copy of this.', '복사하다', 'Copy');
INSERT INTO word (difficulty, example, meaning, word) VALUES (0, 'Save the file now.', '파일', 'File');
INSERT INTO word (difficulty, example, meaning, word) VALUES (0, 'I lost my credit card.', '카드', 'Card');
INSERT INTO word (difficulty, example, meaning, word) VALUES (0, 'The bank is closed.', '은행', 'Bank');
INSERT INTO word (difficulty, example, meaning, word) VALUES (0, 'I need some money.', '돈', 'Money');
INSERT INTO word (difficulty, example, meaning, word) VALUES (0, 'You can pay by cash.', '지불하다', 'Pay');
INSERT INTO word (difficulty, example, meaning, word) VALUES (0, 'Where can I buy this?', '사다', 'Buy');
INSERT INTO word (difficulty, example, meaning, word) VALUES (0, 'They sell fresh bread.', '팔다', 'Sell');
INSERT INTO word (difficulty, example, meaning, word) VALUES (0, 'The shop is open.', '열다', 'Open');
INSERT INTO word (difficulty, example, meaning, word) VALUES (0, 'Please close the door.', '닫다', 'Close');
INSERT INTO word (difficulty, example, meaning, word) VALUES (0, 'When does it start?', '시작하다', 'Start');
INSERT INTO word (difficulty, example, meaning, word) VALUES (0, 'I need to finish this.', '끝내다', 'Finish');
INSERT INTO word (difficulty, example, meaning, word) VALUES (0, 'I want to learn English.', '배우다', 'Learn');
INSERT INTO word (difficulty, example, meaning, word) VALUES (0, 'Can you speak slowly?', '말하다', 'Speak');
INSERT INTO word (difficulty, example, meaning, word) VALUES (0, 'Read the instructions.', '읽다', 'Read');
INSERT INTO word (difficulty, example, meaning, word) VALUES (1, 'Please confirm your reservation.', '확인하다', 'Confirm');
INSERT INTO word (difficulty, example, meaning, word) VALUES (1, 'We deliver orders within three days.', '배달하다', 'Deliver');
INSERT INTO word (difficulty, example, meaning, word) VALUES (1, 'Thank you for your inquiry.', '문의', 'Inquiry');
INSERT INTO word (difficulty, example, meaning, word) VALUES (1, 'Follow the safety policy.', '정책, 규정', 'Policy');
INSERT INTO word (difficulty, example, meaning, word) VALUES (1, 'Submit the report by Friday.', '제출하다', 'Submit');
INSERT INTO word (difficulty, example, meaning, word) VALUES (1, 'The schedule is tight.', '일정', 'Schedule');
INSERT INTO word (difficulty, example, meaning, word) VALUES (1, 'He got a promotion.', '승진, 홍보', 'Promotion');
INSERT INTO word (difficulty, example, meaning, word) VALUES (1, 'Is there a discount?', '할인', 'Discount');
INSERT INTO word (difficulty, example, meaning, word) VALUES (1, 'I want a full refund.', '환불', 'Refund');
INSERT INTO word (difficulty, example, meaning, word) VALUES (1, 'She requested a meeting.', '요청하다', 'Request');
INSERT INTO word (difficulty, example, meaning, word) VALUES (1, 'The equipment is new.', '장비', 'Equipment');
INSERT INTO word (difficulty, example, meaning, word) VALUES (1, 'Check the inventory.', '재고', 'Inventory');
INSERT INTO word (difficulty, example, meaning, word) VALUES (1, 'Please pay the invoice.', '송장', 'Invoice');
INSERT INTO word (difficulty, example, meaning, word) VALUES (1, 'The room is available.', '이용 가능한', 'Available');
INSERT INTO word (difficulty, example, meaning, word) VALUES (1, 'Give me more details.', '세부사항', 'Detail');
INSERT INTO word (difficulty, example, meaning, word) VALUES (1, 'We must improve quality.', '개선하다', 'Improve');
INSERT INTO word (difficulty, example, meaning, word) VALUES (1, 'We provide free wifi.', '제공하다', 'Provide');
INSERT INTO word (difficulty, example, meaning, word) VALUES (1, 'Prepare for the talk.', '준비하다', 'Prepare');
INSERT INTO word (difficulty, example, meaning, word) VALUES (1, 'Contact me anytime.', '연락하다', 'Contact');
INSERT INTO word (difficulty, example, meaning, word) VALUES (1, 'Attend the workshop.', '참석하다', 'Attend');
INSERT INTO word (difficulty, example, meaning, word) VALUES (1, 'The branch is nearby.', '지점', 'Branch');
INSERT INTO word (difficulty, example, meaning, word) VALUES (1, 'Your package arrived.', '패키지, 꾸러미', 'Package');
INSERT INTO word (difficulty, example, meaning, word) VALUES (1, 'Keep your receipt.', '영수증', 'Receipt');
INSERT INTO word (difficulty, example, meaning, word) VALUES (1, 'The benefits are great.', '혜택, 복지', 'Benefit');
INSERT INTO word (difficulty, example, meaning, word) VALUES (1, 'New staff need training.', '교육, 훈련', 'Training');
INSERT INTO word (difficulty, example, meaning, word) VALUES (1, 'Complete the form.', '완료하다', 'Complete');
INSERT INTO word (difficulty, example, meaning, word) VALUES (1, 'Sign the document.', '서류, 문서', 'Document');
INSERT INTO word (difficulty, example, meaning, word) VALUES (1, 'He is an expert.', '전문가', 'Expert');
INSERT INTO word (difficulty, example, meaning, word) VALUES (1, 'The market is growing.', '시장', 'Market');
INSERT INTO word (difficulty, example, meaning, word) VALUES (1, 'That''s a good offer.', '제공, 제안', 'Offer');
INSERT INTO word (difficulty, example, meaning, word) VALUES (1, 'Payment is due today.', '지불', 'Payment');
INSERT INTO word (difficulty, example, meaning, word) VALUES (1, 'Production has stopped.', '생산', 'Production');
INSERT INTO word (difficulty, example, meaning, word) VALUES (1, 'The project is hard.', '프로젝트', 'Project');
INSERT INTO word (difficulty, example, meaning, word) VALUES (1, 'Register for the class.', '등록하다', 'Register');
INSERT INTO word (difficulty, example, meaning, word) VALUES (1, 'Reserve a table.', '예약하다', 'Reserve');
INSERT INTO word (difficulty, example, meaning, word) VALUES (1, 'Wait for a response.', '응답', 'Response');
INSERT INTO word (difficulty, example, meaning, word) VALUES (1, 'Review the contract.', '검토하다', 'Review');
INSERT INTO word (difficulty, example, meaning, word) VALUES (1, 'Go to the next section.', '부분, 구역', 'Section');
INSERT INTO word (difficulty, example, meaning, word) VALUES (1, 'Select an option.', '선택하다', 'Select');
INSERT INTO word (difficulty, example, meaning, word) VALUES (1, 'We found a solution.', '해결책', 'Solution');
INSERT INTO word (difficulty, example, meaning, word) VALUES (1, 'Follow the standard.', '기준', 'Standard');
INSERT INTO word (difficulty, example, meaning, word) VALUES (1, 'I suggest we wait.', '제안하다', 'Suggest');
INSERT INTO word (difficulty, example, meaning, word) VALUES (1, 'We support your idea.', '지원하다', 'Support');
INSERT INTO word (difficulty, example, meaning, word) VALUES (1, 'The system is down.', '시스템', 'System');
INSERT INTO word (difficulty, example, meaning, word) VALUES (1, 'Update your software.', '업데이트', 'Update');
INSERT INTO word (difficulty, example, meaning, word) VALUES (1, 'It is very valuable.', '귀중한', 'Valuable');
INSERT INTO word (difficulty, example, meaning, word) VALUES (1, 'Welcome our visitor.', '방문객', 'Visitor');
INSERT INTO word (difficulty, example, meaning, word) VALUES (1, 'Visit our website.', '웹사이트', 'Website');
INSERT INTO word (difficulty, example, meaning, word) VALUES (1, 'Welcome to the team.', '환영하다', 'Welcome');
INSERT INTO word (difficulty, example, meaning, word) VALUES (1, 'Join the workshop.', '워크숍', 'Workshop');
INSERT INTO word (difficulty, example, meaning, word) VALUES (2, 'Reach an agreement.', '동의, 합의', 'Agreement');
INSERT INTO word (difficulty, example, meaning, word) VALUES (2, 'The boss approved it.', '승인하다', 'Approve');
INSERT INTO word (difficulty, example, meaning, word) VALUES (2, 'Sign the legal contract.', '계약', 'Contract');
INSERT INTO word (difficulty, example, meaning, word) VALUES (2, 'Give me an estimate.', '견적', 'Estimate');
INSERT INTO word (difficulty, example, meaning, word) VALUES (2, 'Postpone the game.', '연기하다', 'Postpone');
INSERT INTO word (difficulty, example, meaning, word) VALUES (2, 'It is not relevant.', '관련 있는', 'Relevant');
INSERT INTO word (difficulty, example, meaning, word) VALUES (2, 'Arrange a meeting.', '배열하다, 주선하다', 'Arrange');
INSERT INTO word (difficulty, example, meaning, word) VALUES (2, 'Compare the two prices.', '비교하다', 'Compare');
INSERT INTO word (difficulty, example, meaning, word) VALUES (2, 'Make a quick decision.', '결정', 'Decision');
INSERT INTO word (difficulty, example, meaning, word) VALUES (2, 'He is a hard employee.', '직원', 'Employee');
INSERT INTO word (difficulty, example, meaning, word) VALUES (2, 'There is no evidence.', '증거', 'Evidence');
INSERT INTO word (difficulty, example, meaning, word) VALUES (2, 'Give us your feedback.', '피드백', 'Feedback');
INSERT INTO word (difficulty, example, meaning, word) VALUES (2, 'We guarantee quality.', '보증하다', 'Guarantee');
INSERT INTO word (difficulty, example, meaning, word) VALUES (2, 'Identify the problem.', '확인하다, 식별하다', 'Identify');
INSERT INTO word (difficulty, example, meaning, word) VALUES (2, 'Sales will increase.', '증가하다', 'Increase');
INSERT INTO word (difficulty, example, meaning, word) VALUES (2, 'He was not involved.', '관련된', 'Involved');
INSERT INTO word (difficulty, example, meaning, word) VALUES (2, 'Maintain the machine.', '유지하다', 'Maintain');
INSERT INTO word (difficulty, example, meaning, word) VALUES (2, 'Negotiate the price.', '협상하다', 'Negotiate');
INSERT INTO word (difficulty, example, meaning, word) VALUES (2, 'What is our objective?', '목표', 'Objective');
INSERT INTO word (difficulty, example, meaning, word) VALUES (2, 'Many oppose the plan.', '반대하다', 'Oppose');
INSERT INTO word (difficulty, example, meaning, word) VALUES (2, 'Perform your duties.', '수행하다', 'Perform');
INSERT INTO word (difficulty, example, meaning, word) VALUES (2, 'Ask for permission.', '허락', 'Permission');
INSERT INTO word (difficulty, example, meaning, word) VALUES (2, 'Predict the future.', '예측하다', 'Predict');
INSERT INTO word (difficulty, example, meaning, word) VALUES (2, 'Purchase the items.', '구매하다', 'Purchase');
INSERT INTO word (difficulty, example, meaning, word) VALUES (2, 'Quality is important.', '품질', 'Quality');
INSERT INTO word (difficulty, example, meaning, word) VALUES (2, 'Focus on quantity.', '수량', 'Quantity');
INSERT INTO word (difficulty, example, meaning, word) VALUES (2, 'I recommend this.', '추천하다', 'Recommend');
INSERT INTO word (difficulty, example, meaning, word) VALUES (2, 'Reduce the costs.', '줄이다', 'Reduce');
INSERT INTO word (difficulty, example, meaning, word) VALUES (2, 'Check his references.', '참고, 추천인', 'Reference');
INSERT INTO word (difficulty, example, meaning, word) VALUES (2, 'He is very reliable.', '신뢰할 수 있는', 'Reliable');
INSERT INTO word (difficulty, example, meaning, word) VALUES (2, 'Replace the battery.', '교체하다', 'Replace');
INSERT INTO word (difficulty, example, meaning, word) VALUES (2, 'Meet the requirements.', '요구사항', 'Requirement');
INSERT INTO word (difficulty, example, meaning, word) VALUES (2, 'Do more research.', '연구', 'Research');
INSERT INTO word (difficulty, example, meaning, word) VALUES (2, 'We lack resources.', '자원', 'Resource');
INSERT INTO word (difficulty, example, meaning, word) VALUES (2, 'It''s my responsibility.', '책임', 'Responsibility');
INSERT INTO word (difficulty, example, meaning, word) VALUES (2, 'The result was good.', '결과', 'Result');
INSERT INTO word (difficulty, example, meaning, word) VALUES (2, 'Customer satisfaction.', '만족', 'Satisfaction');
INSERT INTO word (difficulty, example, meaning, word) VALUES (2, 'The situation changed.', '상황', 'Situation');
INSERT INTO word (difficulty, example, meaning, word) VALUES (2, 'A new strategy.', '전략', 'Strategy');
INSERT INTO word (difficulty, example, meaning, word) VALUES (2, 'Thanks for the suggestion.', '제안', 'Suggestion');
INSERT INTO word (difficulty, example, meaning, word) VALUES (2, 'Read the summary.', '요약', 'Summary');
INSERT INTO word (difficulty, example, meaning, word) VALUES (2, 'Supply the materials.', '공급하다', 'Supply');
INSERT INTO word (difficulty, example, meaning, word) VALUES (2, 'Take our survey.', '설문조사', 'Survey');
INSERT INTO word (difficulty, example, meaning, word) VALUES (2, 'A technical issue.', '기술적인', 'Technical');
INSERT INTO word (difficulty, example, meaning, word) VALUES (2, 'Transfer to Seoul.', '이동하다', 'Transfer');
INSERT INTO word (difficulty, example, meaning, word) VALUES (2, 'Public transport.', '운송', 'Transport');
INSERT INTO word (difficulty, example, meaning, word) VALUES (2, 'This is an urgent matter.', '긴급한', 'Urgent');
INSERT INTO word (difficulty, example, meaning, word) VALUES (2, 'What is the value?', '가치', 'Value');
INSERT INTO word (difficulty, example, meaning, word) VALUES (2, 'Various reasons.', '다양한', 'Various');
INSERT INTO word (difficulty, example, meaning, word) VALUES (2, 'She organized the documents', '정리하다', 'Organize');
INSERT INTO word (difficulty, example, meaning, word) VALUES (3, 'Acquire a new company.', '인수하다, 얻다', 'Acquire');
INSERT INTO word (difficulty, example, meaning, word) VALUES (3, 'Implement the changes.', '시행하다', 'Implement');
INSERT INTO word (difficulty, example, meaning, word) VALUES (3, 'Attendance is mandatory.', '의무적인', 'Mandatory');
INSERT INTO word (difficulty, example, meaning, word) VALUES (3, 'Prospective clients.', '잠재적인', 'Prospective');
INSERT INTO word (difficulty, example, meaning, word) VALUES (3, 'A versatile tool.', '다재다능한', 'Versatile');
INSERT INTO word (difficulty, example, meaning, word) VALUES (3, 'Allocate the budget.', '할당하다', 'Allocate');
INSERT INTO word (difficulty, example, meaning, word) VALUES (3, 'A detailed analysis.', '분석', 'Analysis');
INSERT INTO word (difficulty, example, meaning, word) VALUES (3, 'Anticipate the need.', '예상하다', 'Anticipate');
INSERT INTO word (difficulty, example, meaning, word) VALUES (3, 'Collaborate with peers.', '협력하다', 'Collaborate');
INSERT INTO word (difficulty, example, meaning, word) VALUES (3, 'The event will commence.', '시작하다', 'Commence');
INSERT INTO word (difficulty, example, meaning, word) VALUES (3, 'Compensate for loss.', '보상하다', 'Compensate');
INSERT INTO word (difficulty, example, meaning, word) VALUES (3, 'A comprehensive plan.', '포괄적인', 'Comprehensive');
INSERT INTO word (difficulty, example, meaning, word) VALUES (3, 'Reach a conclusion.', '결론', 'Conclusion');
INSERT INTO word (difficulty, example, meaning, word) VALUES (3, 'Conduct a survey.', '수행하다', 'Conduct');
INSERT INTO word (difficulty, example, meaning, word) VALUES (3, 'Consistent results.', '일관된', 'Consistent');
INSERT INTO word (difficulty, example, meaning, word) VALUES (3, 'Budget constraints.', '제약', 'Constraint');
INSERT INTO word (difficulty, example, meaning, word) VALUES (3, 'Contribute to a cause.', '기여하다', 'Contribute');
INSERT INTO word (difficulty, example, meaning, word) VALUES (3, 'A crucial decision.', '결정적인', 'Crucial');
INSERT INTO word (difficulty, example, meaning, word) VALUES (3, 'Demonstrate the use.', '증명하다', 'Demonstrate');
INSERT INTO word (difficulty, example, meaning, word) VALUES (3, 'Determine the cause.', '결정하다', 'Determine');
INSERT INTO word (difficulty, example, meaning, word) VALUES (3, 'Distribute the flyers.', '배포하다', 'Distribute');
INSERT INTO word (difficulty, example, meaning, word) VALUES (3, 'An efficient system.', '효율적인', 'Efficient');
INSERT INTO word (difficulty, example, meaning, word) VALUES (3, 'Eliminate the errors.', '제거하다', 'Eliminate');
INSERT INTO word (difficulty, example, meaning, word) VALUES (3, 'Emphasize the point.', '강조하다', 'Emphasize');
INSERT INTO word (difficulty, example, meaning, word) VALUES (3, 'Encounter a problem.', '직면하다', 'Encounter');
INSERT INTO word (difficulty, example, meaning, word) VALUES (3, 'Enhance the photo.', '향상시키다', 'Enhance');
INSERT INTO word (difficulty, example, meaning, word) VALUES (3, 'Establish a company.', '설립하다', 'Establish');
INSERT INTO word (difficulty, example, meaning, word) VALUES (3, 'Annual evaluation.', '평가', 'Evaluation');
INSERT INTO word (difficulty, example, meaning, word) VALUES (3, 'Exceed the limit.', '초과하다', 'Exceed');
INSERT INTO word (difficulty, example, meaning, word) VALUES (3, 'Business expansion.', '확장', 'Expansion');
INSERT INTO word (difficulty, example, meaning, word) VALUES (3, 'Prices fluctuate.', '변동하다', 'Fluctuate');
INSERT INTO word (difficulty, example, meaning, word) VALUES (3, 'A fundamental right.', '근본적인', 'Fundamental');
INSERT INTO word (difficulty, example, meaning, word) VALUES (3, 'Generate more profit.', '발생시키다', 'Generate');
INSERT INTO word (difficulty, example, meaning, word) VALUES (3, 'Offer an incentive.', '인센티브', 'Incentive');
INSERT INTO word (difficulty, example, meaning, word) VALUES (3, 'The graph indicates...', '나타내다', 'Indicate');
INSERT INTO word (difficulty, example, meaning, word) VALUES (3, 'It is inevitable.', '불가피한', 'Inevitable');
INSERT INTO word (difficulty, example, meaning, word) VALUES (3, 'Constant innovation.', '혁신', 'Innovation');
INSERT INTO word (difficulty, example, meaning, word) VALUES (3, 'Software installation.', '설치', 'Installation');
INSERT INTO word (difficulty, example, meaning, word) VALUES (3, 'Follow instructions.', '설명서', 'Instructions');
INSERT INTO word (difficulty, example, meaning, word) VALUES (3, 'Under investigation.', '조사', 'Investigation');
INSERT INTO word (difficulty, example, meaning, word) VALUES (3, 'Minor modification.', '수정', 'Modification');
INSERT INTO word (difficulty, example, meaning, word) VALUES (3, 'Peace negotiations.', '협상', 'Negotiation');
INSERT INTO word (difficulty, example, meaning, word) VALUES (3, 'Send a notification.', '통보', 'Notification');
INSERT INTO word (difficulty, example, meaning, word) VALUES (3, 'Legal obligation.', '의무', 'Obligation');
INSERT INTO word (difficulty, example, meaning, word) VALUES (3, 'Overcome obstacles.', '장애물', 'Obstacle');
INSERT INTO word (difficulty, example, meaning, word) VALUES (3, 'Many participants.', '참가자', 'Participant');
INSERT INTO word (difficulty, example, meaning, word) VALUES (3, 'A precise timing.', '정밀한', 'Precise');
INSERT INTO word (difficulty, example, meaning, word) VALUES (3, 'Our top priority.', '우선순위', 'Priority');
INSERT INTO word (difficulty, example, meaning, word) VALUES (3, 'Standard procedure.', '절차', 'Procedure');
INSERT INTO word (difficulty, example, meaning, word) VALUES (3, 'A significant change.', '중요한', 'Significant');
INSERT INTO word (difficulty, example, meaning, word) VALUES (4, 'Affected adversely.', '불리하게', 'Adversely');
INSERT INTO word (difficulty, example, meaning, word) VALUES (4, 'Contingency plan.', '만일의 사태', 'Contingency');
INSERT INTO word (difficulty, example, meaning, word) VALUES (4, 'Exemplary behavior.', '모범적인', 'Exemplary');
INSERT INTO word (difficulty, example, meaning, word) VALUES (4, 'Prevalent disease.', '널리 퍼진', 'Prevalent');
INSERT INTO word (difficulty, example, meaning, word) VALUES (4, 'The rules stipulate...', '규정하다', 'Stipulate');
INSERT INTO word (difficulty, example, meaning, word) VALUES (4, 'An ambiguous answer.', '모호한', 'Ambiguous');
INSERT INTO word (difficulty, example, meaning, word) VALUES (4, 'Performance appraisal.', '평가', 'Appraisal');
INSERT INTO word (difficulty, example, meaning, word) VALUES (4, 'An arbitrary choice.', '임의적인', 'Arbitrary');
INSERT INTO word (difficulty, example, meaning, word) VALUES (4, 'Commensurate with skill.', '비례하는', 'Commensurate');
INSERT INTO word (difficulty, example, meaning, word) VALUES (4, 'A concise summary.', '간결한', 'Concise');
INSERT INTO word (difficulty, example, meaning, word) VALUES (4, 'Consolidate the debts.', '통합하다', 'Consolidate');
INSERT INTO word (difficulty, example, meaning, word) VALUES (4, 'The new curriculum.', '커리큘럼', 'Curriculum');
INSERT INTO word (difficulty, example, meaning, word) VALUES (4, 'Delegate the tasks.', '위임하다', 'Delegate');
INSERT INTO word (difficulty, example, meaning, word) VALUES (4, 'Cars depreciate.', '가치가 떨어지다', 'Depreciate');
INSERT INTO word (difficulty, example, meaning, word) VALUES (4, 'A discrepancy in data.', '불일치', 'Discrepancy');
INSERT INTO word (difficulty, example, meaning, word) VALUES (4, 'At your discretion.', '재량', 'Discretion');
INSERT INTO word (difficulty, example, meaning, word) VALUES (4, 'Weather deteriorated.', '악화되다', 'Deteriorate');
INSERT INTO word (difficulty, example, meaning, word) VALUES (4, 'A drastic change.', '급격한', 'Drastic');
INSERT INTO word (difficulty, example, meaning, word) VALUES (4, 'Eligible for a prize.', '자격이 있는', 'Eligible');
INSERT INTO word (difficulty, example, meaning, word) VALUES (4, 'Endorse a product.', '지지하다', 'Endorse');
INSERT INTO word (difficulty, example, meaning, word) VALUES (4, 'Exert influence.', '발휘하다', 'Exert');
INSERT INTO word (difficulty, example, meaning, word) VALUES (4, 'A feasible plan.', '실행 가능한', 'Feasible');
INSERT INTO word (difficulty, example, meaning, word) VALUES (4, 'Hinder progress.', '방해하다', 'Hinder');
INSERT INTO word (difficulty, example, meaning, word) VALUES (4, 'Incur a loss.', '초래하다', 'Incur');
INSERT INTO word (difficulty, example, meaning, word) VALUES (4, 'Inherent danger.', '내재된', 'Inherent');
INSERT INTO word (difficulty, example, meaning, word) VALUES (4, 'Professional integrity.', '정직, 성실', 'Integrity');
INSERT INTO word (difficulty, example, meaning, word) VALUES (4, 'An intricate design.', '복잡한', 'Intricate');
INSERT INTO word (difficulty, example, meaning, word) VALUES (4, 'The official liaison.', '연락 담당자', 'Liaison');
INSERT INTO word (difficulty, example, meaning, word) VALUES (4, 'A lucrative deal.', '수익성이 좋은', 'Lucrative');
INSERT INTO word (difficulty, example, meaning, word) VALUES (4, 'Manifest changes.', '분명히 나타내다', 'Manifest');
INSERT INTO word (difficulty, example, meaning, word) VALUES (4, 'Meticulous work.', '꼼꼼한', 'Meticulous');
INSERT INTO word (difficulty, example, meaning, word) VALUES (4, 'A nominal fee.', '명목상의', 'Nominal');
INSERT INTO word (difficulty, example, meaning, word) VALUES (4, 'Oversee the work.', '감독하다', 'Oversee');
INSERT INTO word (difficulty, example, meaning, word) VALUES (4, 'Pervasive influence.', '만연한', 'Pervasive');
INSERT INTO word (difficulty, example, meaning, word) VALUES (4, 'A plausible excuse.', '그럴듯한', 'Plausible');
INSERT INTO word (difficulty, example, meaning, word) VALUES (4, 'Required prerequisite.', '전제 조건', 'Prerequisite');
INSERT INTO word (difficulty, example, meaning, word) VALUES (4, 'A man of prestige.', '명성', 'Prestige');
INSERT INTO word (difficulty, example, meaning, word) VALUES (4, 'A prosperous year.', '번영하는', 'Prosperous');
INSERT INTO word (difficulty, example, meaning, word) VALUES (4, 'The award recipient.', '수령인', 'Recipient');
INSERT INTO word (difficulty, example, meaning, word) VALUES (4, 'Redundant system.', '불필요한', 'Redundant');
INSERT INTO word (difficulty, example, meaning, word) VALUES (4, 'Renovate the house.', '개조하다', 'Renovate');
INSERT INTO word (difficulty, example, meaning, word) VALUES (4, 'A good reputation.', '평판', 'Reputation');
INSERT INTO word (difficulty, example, meaning, word) VALUES (4, 'Resilient economy.', '회복력 있는', 'Resilient');
INSERT INTO word (difficulty, example, meaning, word) VALUES (4, 'Speculate on results.', '추측하다', 'Speculate');
INSERT INTO word (difficulty, example, meaning, word) VALUES (4, 'Stringent rules.', '엄격한', 'Stringent');
INSERT INTO word (difficulty, example, meaning, word) VALUES (4, 'Substantial amount.', '상당한', 'Substantial');
INSERT INTO word (difficulty, example, meaning, word) VALUES (4, 'Tangible assets.', '유형의, 만질 수 있는', 'Tangible');
INSERT INTO word (difficulty, example, meaning, word) VALUES (4, 'A tedious task.', '지루한', 'Tedious');
INSERT INTO word (difficulty, example, meaning, word) VALUES (4, 'Transparent process.', '투명한', 'Transparent');
INSERT INTO word (difficulty, example, meaning, word) VALUES (4, 'A unanimous vote.', '만장일치의', 'Unanimous');